name: Build
on:
  push:
    branch:
      - 'master'

jobs:

  build-mac:
    runs-on: macos-latest

    env:
      NODE_ENV: production
      NPM_CONFIG_PRODUCTION: false
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_API_KEY: ${{ github.workspace }}/AuthKey_${{secrets.APPLE_API_KEY_ID}}.p8
      APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_CONTENT }}
      APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
      APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
      DEBUG: electron-osx-sign*

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install canvas deps
        run: brew install pkg-config cairo pango libpng jpeg giflib librsvg python-setuptools

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install deps
        run: npm ci

      - name: install native deps
        run: npx electron-builder install-app-deps

      - name: Build launcher
        run: npx electron-vite build

      - name: Package launcher (signed)
        run: |
          echo "$APPLE_API_KEY_CONTENT" >> $APPLE_API_KEY
          npx electron-builder --config electron-builder.yml --mac
